.\" Copyright (c) 2018 Jan Stary <hans@stare.cz>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd June 28, 2018
.Dt RTP 1
.Os
.Sh NAME
.Nm rtp
.Nd debug RTP sessions
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl i Ar format
.Op Fl o Ar format
.Op input
.Op output
.Sh DESCRIPTION
.Nm
reads a stream of RTP packets from
.Ar input
and writes it to
.Ar output .
Both can be a named file or a network address.
By default,
.Nm
reads from standard input and writes to standard output.
A name of
.Sq -
also means standard input or output.
A network address is given as
.Oo Ar address Oc Ns Ar :port ,
where
.Ar address
is either an IP address in dot-decimal notation or a hostname
.Po
.Dq localhost
by default
.Pc ,
and
.Ar port
is a number.
.Pp
If the
.Ar output
is a local address
(i.e. an address assigned to a network interface of the local machine),
.Nm
will wait till someone sends a one-byte message to that address
and then will stream the input to them.
Similarly, if the
.Ar input
is a remote address,
.Nm
will try to send a one-byte message first to let them know we are reading.
For other combinations of input and output,
.Nm
behaves in the obvious way.
.Pp
The stream can be read or written in the following formats:
.Bl -tag -width Ds
.It Cm dump
The format of the original rtptools (see below).
A dump file starts with a txt line of the form
.Dq #!rtptools1.0 addr/port ,
followed by a dumpfile header:
.Bd -literal
struct dumphdr {
	struct {
		uint32_t sec;
		uint32_t usec;
	}		time;
	uint32_t	addr;
	uint16_t	port;
	uint16_t	zero;
};
.Ed
.Pp
When reading,
.Nm
ignores the starting line
and the addr and port stored in the above header.
When writing,
.Nm
sets them to zero.
.Pp
The actual RTP packets follow, each prefixed with:
.Bd -literal
struct dpkthdr {
	uint16_t dlen; /* stored packet length, including this   */
	uint16_t plen; /* original RTP (header + payload) length */
	uint32_t usec; /* dump time: usec since start time       */
};
.Ed
.Pp
If the payload was truncated during dump (see the
.Fl x
option),
.\"FIXME
dlen will be shorter than plen.
The RTP header is always there.
All fields are stored in the network byte order.
.It Cm net
The actual RTP packets being sent and received.
This is the only format used with network connections.
.It Cm raw
The actual audio payload of the RTP packet.
This format can only be used as an output to a file.
.Nm
has no support for the actual audio
and will not deal with the audio codec involved.
.It Cm ascii
RTP packets described with lines of text.
.El
.Pp
For regular files, the format will be guessed from the file name suffix:
.Dq rtp
for
.Cm dump ,
.Dq raw
for
.Cm raw ,
and
.Dq txt
for
.Cm ascii ,
with
.Cm dump
being the default if the format cannot be guessed from the name.
.Pp
The options are as follows.
.Pp
.Bl -tag -compact -width formatxxx
.It Fl i Ar format
Set the input format.
.It Fl o Ar format
Set the output format.
.It Fl v
Be verbose.
.El
.Sh EXAMPLES
Read from a dump file, write the raw audio payload:
.Dl $ rtp infile outfile.raw
.Pp
Read from a dump file, stream as rtp to whoever connects to us:
.Dl $ rtp infile 192.168.1.1:1234
.Pp
Read from a dump file, stream as rtp to a remote location:
.Dl $ rtp infile host.domain.com:1234
.Pp
Read rtp on a local port, write to an ascii file:
.Dl $ rtp 192.168.1.1:1234 outfile.txt
.Pp
Read rtp on a local port, stream it out on another port:
.Dl $ rtp -o raw 192.168.1.1:1234 192.168.12.34:6666
.Pp
Read rtp on a local port, stream it to a remote location:
.Dl $ rtp 192.168.1.1:1234 host.domain.com:6666
.Pp
Read rtp from a remote location, write audio payload to stdout:
.Dl $ rtp -o raw host.domain.com:1234
.Sh HISTORY
In the early days of RTP, Henning Schulzrinne wrote a set of
.Dq rtptools
to debug RTP sessions;
.Nm
is a replacement, written from scratch.
Reading a local port and dumping it to a file is rtpdump.
Streaming a file to a remote location is rtpplay and rtpsend.
Reading from an address and streaming to another address is rtptrans.
.Sh AUTHORS
.An Jan Starý Aq Mt hans@stare.cz
.Sh BUGS
By convention, RTP traffic happens on an even port number,
and the corresponding RTCP happens on the odd port+1.
.Nm
ignores that convention, only reads the specified
.Ar port ,
and misses the RTCP packets.
